modLoader = "javafml" #mandatory
loaderVersion = "*" #mandatory
license = "${license_url}" # Review your options at https://choosealicense.com/.
issueTrackerURL = "${issues_url}" #optional

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${version}" #mandatory
displayName = "${mod_display_name}" #mandatory
displayURL = "${homepage_url}" #optional (displayed in the mod UI)
logoFile = "icon.png" #optional
#credits = "" #optional
authors = "Cammie, Up" #optional
description = '''${mod_description}''' #mandatory (Supports multiline text)

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

# https://docs.neoforged.net/docs/gettingstarted/modfiles#dependency-configurations
[dependencies]
    "${mod_id}" = [
        { modId = "neoforge", type = 'required', versionRange = "*", ordering = "NONE", side = "BOTH", mc-publish = { ignore = true } },
        { modId = "minecraft", type = 'required', versionRange = "[${minecraft_version}]", ordering = "NONE", side = "BOTH" },
        { modId = "curios", type = 'required', versionRange = "[5.8.0,)", ordering = "NONE", side = "BOTH", mc-publish = { curseforge = "309927", modrinth = "vvuO3ImH" } },
        { modId = "caelus", type = 'required', versionRange = "*", ordering = "NONE", side = "BOTH", mc-publish = { curseforge = "308989", modrinth = "40FYwb4z" } },
        { modId = "resourcefulconfig", type = 'required', versionRange = "*", ordering = "NONE", side = "BOTH", mc-publish = { curseforge = "714059", modrinth = "M1953qlQ" } },
        { modId = "commonnetworking", type = 'required', versionRange = "*", ordering = "NONE", side = "BOTH", mc-publish = { curseforge = "806044", modrinth = "HIuqnQpi" } },
        { modId = "camera_overhaul_neoforge", type = 'optional', versionRange = "[1.1,)", ordering = "NONE", side = "CLIENT", mc-publish = { curseforge = "1011593", modrinth = "LwcpSm6L" } }
    ]

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"

[mc-publish]
    curseforge = "${curseforge_id}"
    modrinth = "${modrinth_id}"
    loaders = [
        "neoforge",
        "forge"
    ]
    dependencies = [
        "camera_overhaul_neoforge(optional){modrinth:LwcpSm6L}{curseforge:1011593}",
        "figura(optional){modrinth:s9gIPDom}{curseforge:901503}"
    ]
